/**
 * Client-side PDF generation for brag documents.
 * Uses jsPDF + jspdf-autotable.
 */

import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import type { BragDocument } from './db';

export async function exportBragDocToPDF(doc: BragDocument, userName: string): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Header
  pdf.setFontSize(10);
  pdf.setTextColor(120, 120, 120);
  pdf.text('QUIETCAREER', margin, 15);
  pdf.text('CONFIDENTIAL', pageWidth - margin, 15, { align: 'right' });

  // Thin separator
  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.3);
  pdf.line(margin, 18, pageWidth - margin, 18);

  // Title
  pdf.setFontSize(20);
  pdf.setTextColor(30, 30, 30);
  pdf.text(doc.title, margin, 30);

  // Meta
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(
    `${userName} | ${doc.dateRangeStart} to ${doc.dateRangeEnd} | ${doc.includedLogIds.length} entries`,
    margin,
    37
  );

  // Content
  pdf.setFontSize(11);
  pdf.setTextColor(40, 40, 40);

  const content = doc.editedContent || doc.generatedContent;
  const lines = pdf.splitTextToSize(content, contentWidth);

  let y = 48;
  const lineHeight = 5.5;
  const pageHeight = pdf.internal.pageSize.getHeight();

  for (const line of lines) {
    if (y > pageHeight - 25) {
      pdf.addPage();
      y = 20;
    }
    pdf.text(line, margin, y);
    y += lineHeight;
  }

  // Footer
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Generated by QuietCareer | Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Download
  const filename = `${doc.title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}.pdf`;
  pdf.save(filename);
}

export async function exportWorkLogsToPDF(
  logs: { date: string; content: string; aiRewrite: string | null; impactType: string; project: string }[],
  userName: string,
  dateRange: string
): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;

  // Header
  pdf.setFontSize(18);
  pdf.setTextColor(30, 30, 30);
  pdf.text('Field Notes Export', margin, 20);

  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`${userName} | ${dateRange} | ${logs.length} entries`, margin, 27);

  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.3);
  pdf.line(margin, 30, pageWidth - margin, 30);

  // Table
  const tableData = logs.map((log) => [
    log.date,
    log.project || '-',
    log.impactType,
    log.aiRewrite || log.content,
  ]);

  (pdf as unknown as { autoTable: (opts: unknown) => void }).autoTable({
    startY: 35,
    head: [['Date', 'Project', 'Type', 'Description']],
    body: tableData,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      textColor: [40, 40, 40],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: [201, 168, 76], // accent gold
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 248, 245],
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 30 },
      2: { cellWidth: 20 },
      3: { cellWidth: 'auto' },
    },
  });

  pdf.save(`work-journal-${dateRange.replace(/\s/g, '-')}.pdf`);
}
